In [1]:
import pandas as pd
import numpy as np
import math

import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

fifa_df = pd.read_csv('fifa21_train.csv')

fifa_df.shape

(11701, 101)

## Understand the Data

In [2]:
fifa_df

,ID,Name,Age,Nationality,Club,BP,Position,Team & Contract,Height,Weight,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,184383,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,...,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,188044,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,...,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,184431,S. Giovinco,33,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,...,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,233796,J. Evans,22,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,...,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,234799,Y. Demoncy,23,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,...,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,232504,B. Böðvarsson,25,Iceland,Jagiellonia Białystok,LB,LB,Jagiellonia Białystok 2018 ~ 2021,"6'1""",168lbs,...,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2,65
11697,214680,G. Gallon,27,France,ESTAC Troyes,GK,GK,ESTAC Troyes 2019 ~ 2022,"6'1""",174lbs,...,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2,70
11698,221489,J. Flores,22,Chile,CD Antofagasta,RM,LM CAM RM,CD Antofagasta 2019 ~ 2024,"5'6""",143lbs,...,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2,67
11699,146717,Anderson Silva,26,Brazil,Barnsley,CM,NaN,Barnsley 2010,"6'2""",179lbs,...,68+0,68+0,66+0,64+0,60+0,60+0,60+0,64+0,25+0,68
11700,236507,T. Conechny,22,Argentina,Portland Timbers,CAM,ST CAM LM,Portland Timbers 2019 ~ 2020,"5'7""",143lbs,...,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2,64

In [3]:
fifa_df.columns.values

array(['ID', 'Name', 'Age', 'Nationality', 'Club', 'BP', 'Position',
       'Team & Contract', 'Height', 'Weight', 'foot', 'Growth', 'Joined',
       'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Contract',
       'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy',
       'Short Passing', 'Volleys', 'Skill', 'Dribbling', 'Curve',
       'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength',
       'Long Shots', 'Mentality', 'Aggression', 'Interceptions',
       'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W',
       'D/W', 'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits',
       'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM',
       'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM',
       'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'GK', 'OVA'], dtype=object)

## Clean the data

In [4]:
fifa_df = fifa_df.drop(['ID', 'Name', 'Club', 'Hits', 'Nationality', 'Position','Team & Contract','Height','Weight', 'foot','Joined','Loan Date End','Wage','Release Clause','Contract'], axis=1)

fifa_df.columns.values

array(['Age', 'BP', 'Growth', 'Value', 'Attacking', 'Crossing',
       'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed',
       'Agility', 'Reactions', 'Balance', 'Power', 'Shot Power',
       'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Mentality',
       'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking',
       'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'GK Diving',
       'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes',
       'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR',
       'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'LS', 'ST', 'RS', 'LW',
       'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM',
       'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
       'RCB', 'RB', 'GK', 'OVA'], dtype=object)

In [5]:
# drop duplicates

fifa_df.drop_duplicates()

,Age,BP,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,26,CM,1,€525K,258,54,47,43,70,44.0,...,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,30,ST,0,€8.5M,365,66,79,76,68,76.0,...,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,33,CAM,0,€9M,336,73,76,34,78,75.0,...,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,22,CDM,13,€275K,242,44,42,58,62,36.0,...,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,23,CDM,8,€725K,249,49,37,61,68,34.0,...,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,25,LB,5,€625K,224,62,24,51,59,28.0,...,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2,65
11697,27,GK,4,€1.6M,84,12,14,13,29,16.0,...,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2,70
11698,22,RM,8,€1.1M,286,64,66,51,64,41.0,...,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2,67
11699,26,CM,7,€0,254,64,66,51,73,NaN,...,68+0,68+0,66+0,64+0,60+0,60+0,60+0,64+0,25+0,68
11700,22,CAM,9,€700K,289,43,64,65,64,53.0,...,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2,64

In [6]:
# nan_positions_tuples = list(zip(*np.where(fifa_df.isna())))
# print(nan_positions_tuples)

fifa_df.columns[fifa_df.isna().any()].tolist()

['Volleys',
 'Curve',
 'Agility',
 'Balance',
 'Jumping',
 'Interceptions',
 'Positioning',
 'Vision',
 'Composure',
 'Sliding Tackle',
 'A/W',
 'D/W']

In [7]:
# filling NaN values with mean and mode

volleys_mean = fifa_df['Volleys'].mean()
curve_mean = fifa_df['Curve'].mean()
agility_mean = fifa_df['Agility'].mean()
balance_mean = fifa_df['Balance'].mean()
jumping_mean = fifa_df['Jumping'].mean()
interceptions_mean = fifa_df['Interceptions'].mean()
positioning_mean = fifa_df['Positioning'].mean()
visions_mean = fifa_df['Vision'].mean()
composure_mean = fifa_df['Composure'].mean()
sliding_mean = fifa_df['Sliding Tackle'].mean()
aw_mode = fifa_df['A/W'].mode()[0]
dw_mode = fifa_df['D/W'].mode()[0]


fifa_df['Volleys'].fillna(volleys_mean, inplace=True)
fifa_df['Curve'].fillna(curve_mean, inplace=True)
fifa_df['Agility'].fillna(agility_mean, inplace=True)
fifa_df['Balance'].fillna(balance_mean, inplace=True)
fifa_df['Jumping'].fillna(jumping_mean, inplace=True)
fifa_df['Interceptions'].fillna(interceptions_mean, inplace=True)
fifa_df['Positioning'].fillna(positioning_mean, inplace=True)
fifa_df['Vision'].fillna(visions_mean, inplace=True)
fifa_df['Composure'].fillna(composure_mean, inplace=True)
fifa_df['Sliding Tackle'].fillna(sliding_mean, inplace=True)
fifa_df['A/W'].fillna(aw_mode, inplace=True)
fifa_df['D/W'].fillna(dw_mode, inplace=True)

# check again for any NaN values

fifa_df.columns[fifa_df.isna().any()].tolist()

[]

In [8]:
# replace ★ values within columns

fifa_df['W/F'].str.replace('★', '')
fifa_df['SM'].str.replace('★', '')
fifa_df['IR'].str.replace('★', '')

0        1
1        2
2        2
3        1
4        1
         ..
11696    1
11697    1
11698    1
11699    3
11700    1
Name: IR, Length: 11701, dtype: object

In [9]:
def sum_values(value_str):
    values = value_str.split('+')
    return sum(map(int, values))

columns_to_change = ['LS', 'ST', 'RS','LW', 'LF', 'CF', 'RF', 'RW', 'LAM','CAM', 'RAM', 'LM', 'LCM','CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB','CB', 'RCB', 'RB', 'GK']

fifa_df[columns_to_change] = fifa_df[columns_to_change].applymap(sum_values)
fifa_df[columns_to_change] = fifa_df[columns_to_change].astype(int)

In [10]:
def convert_currency (value):
    if 'K' in value:
        return float(value.replace('€', '').replace('K', '')) * 1000
    elif 'M' in value:
        return float(value.replace('€', '').replace('M', '')) * 1000000
    else:
        return float(value.replace('€', ''))
    
fifa_df['Value'] = fifa_df['Value'].apply(convert_currency)

print(fifa_df['Value'])

0         525000.0
1        8500000.0
2        9000000.0
3         275000.0
4         725000.0
           ...
11696     625000.0
11697    1600000.0
11698    1100000.0
11699          0.0
11700     700000.0
Name: Value, Length: 11701, dtype: float64

In [11]:
fifa_df.shape

(11701, 86)

In [12]:
# Cluster the best positions into key areas within the field Forwards, Midfielders, Defenders and Goalkeepers.

# fifa_df['BP'] = fifa_df['BP'].replace({'RB':'DEF', 'LB':'DEF', 'CB':'DEF', 'LWB' : 'DEF', 'RWB':'DEF'})
# fifa_df['BP'] = fifa_df['BP'].replace({'RW':'MID', 'LW':'MID', 'RM':'MID', 'LM' : 'MID', 'CDM':'MID', 'CAM':'MID','CM':'MID'})
# fifa_df['BP'] = fifa_df['BP'].replace({'ST': 'FWD', 'CF': 'FWD'})

In [13]:
# for column_name, dtype in fifa_df.dtypes.items():
#     print("Column:", {column_name}, "Data Type:", {dtype})

for i, (column_name, dtype) in enumerate(fifa_df.dtypes.items()):
    print("Column:",{column_name}, "Position:",{i},"DataType:",{dtype})

Column: {'Age'} Position: {0} DataType: {dtype('int64')}
Column: {'BP'} Position: {1} DataType: {dtype('O')}
Column: {'Growth'} Position: {2} DataType: {dtype('int64')}
Column: {'Value'} Position: {3} DataType: {dtype('float64')}
Column: {'Attacking'} Position: {4} DataType: {dtype('int64')}
Column: {'Crossing'} Position: {5} DataType: {dtype('int64')}
Column: {'Finishing'} Position: {6} DataType: {dtype('int64')}
Column: {'Heading Accuracy'} Position: {7} DataType: {dtype('int64')}
Column: {'Short Passing'} Position: {8} DataType: {dtype('int64')}
Column: {'Volleys'} Position: {9} DataType: {dtype('float64')}
Column: {'Skill'} Position: {10} DataType: {dtype('int64')}
Column: {'Dribbling'} Position: {11} DataType: {dtype('int64')}
Column: {'Curve'} Position: {12} DataType: {dtype('float64')}
Column: {'FK Accuracy'} Position: {13} DataType: {dtype('int64')}
Column: {'Long Passing'} Position: {14} DataType: {dtype('int64')}
Column: {'Ball Control'} Position: {15} DataType: {dtype('int64')}
Column: {'Movement'} Position: {16} DataType: {dtype('int64')}
Column: {'Acceleration'} Position: {17} DataType: {dtype('int64')}
Column: {'Sprint Speed'} Position: {18} DataType: {dtype('int64')}
Column: {'Agility'} Position: {19} DataType: {dtype('float64')}
Column: {'Reactions'} Position: {20} DataType: {dtype('int64')}
Column: {'Balance'} Position: {21} DataType: {dtype('float64')}
Column: {'Power'} Position: {22} DataType: {dtype('int64')}
Column: {'Shot Power'} Position: {23} DataType: {dtype('int64')}
Column: {'Jumping'} Position: {24} DataType: {dtype('float64')}
Column: {'Stamina'} Position: {25} DataType: {dtype('int64')}
Column: {'Strength'} Position: {26} DataType: {dtype('int64')}
Column: {'Long Shots'} Position: {27} DataType: {dtype('int64')}
Column: {'Mentality'} Position: {28} DataType: {dtype('int64')}
Column: {'Aggression'} Position: {29} DataType: {dtype('int64')}
Column: {'Interceptions'} Position: {30} DataType: {dtype('float64')}
Column: {'Positioning'} Position: {31} DataType: {dtype('float64')}
Column: {'Vision'} Position: {32} DataType: {dtype('float64')}
Column: {'Penalties'} Position: {33} DataType: {dtype('int64')}
Column: {'Composure'} Position: {34} DataType: {dtype('float64')}
Column: {'Defending'} Position: {35} DataType: {dtype('int64')}
Column: {'Marking'} Position: {36} DataType: {dtype('int64')}
Column: {'Standing Tackle'} Position: {37} DataType: {dtype('int64')}
Column: {'Sliding Tackle'} Position: {38} DataType: {dtype('float64')}
Column: {'Goalkeeping'} Position: {39} DataType: {dtype('int64')}
Column: {'GK Diving'} Position: {40} DataType: {dtype('int64')}
Column: {'GK Handling'} Position: {41} DataType: {dtype('int64')}
Column: {'GK Kicking'} Position: {42} DataType: {dtype('int64')}
Column: {'GK Positioning'} Position: {43} DataType: {dtype('int64')}
Column: {'GK Reflexes'} Position: {44} DataType: {dtype('int64')}
Column: {'Total Stats'} Position: {45} DataType: {dtype('int64')}
Column: {'Base Stats'} Position: {46} DataType: {dtype('int64')}
Column: {'W/F'} Position: {47} DataType: {dtype('O')}
Column: {'SM'} Position: {48} DataType: {dtype('O')}
Column: {'A/W'} Position: {49} DataType: {dtype('O')}
Column: {'D/W'} Position: {50} DataType: {dtype('O')}
Column: {'IR'} Position: {51} DataType: {dtype('O')}
Column: {'PAC'} Position: {52} DataType: {dtype('int64')}
Column: {'SHO'} Position: {53} DataType: {dtype('int64')}
Column: {'PAS'} Position: {54} DataType: {dtype('int64')}
Column: {'DRI'} Position: {55} DataType: {dtype('int64')}
Column: {'DEF'} Position: {56} DataType: {dtype('int64')}
Column: {'PHY'} Position: {57} DataType: {dtype('int64')}
Column: {'LS'} Position: {58} DataType: {dtype('int64')}
Column: {'ST'} Position: {59} DataType: {dtype('int64')}
Column: {'RS'} Position: {60} DataType: {dtype('int64')}
Column: {'LW'} Position: {61} DataType: {dtype('int64')}
Column: {'LF'} Position: {62} DataType: {dtype('int64')}
Column: {'CF'} Position: {63} DataType: {dtype('int64')}
Column: {'RF'} Position: {64} DataType: {dtype('int64')}
Column: {'RW'} Position: {65} DataType: {dtype('int64')}
Column: {'LAM'} Position: {66} DataType: {dtype('int64')}
Column: {'CAM'} Position: {67} DataType: {dtype('int64')}
Column: {'RAM'} Position: {68} DataType: {dtype('int64')}
Column: {'LM'} Position: {69} DataType: {dtype('int64')}
Column: {'LCM'} Position: {70} DataType: {dtype('int64')}
Column: {'CM'} Position: {71} DataType: {dtype('int64')}
Column: {'RCM'} Position: {72} DataType: {dtype('int64')}
Column: {'RM'} Position: {73} DataType: {dtype('int64')}
Column: {'LWB'} Position: {74} DataType: {dtype('int64')}
Column: {'LDM'} Position: {75} DataType: {dtype('int64')}
Column: {'CDM'} Position: {76} DataType: {dtype('int64')}
Column: {'RDM'} Position: {77} DataType: {dtype('int64')}
Column: {'RWB'} Position: {78} DataType: {dtype('int64')}
Column: {'LB'} Position: {79} DataType: {dtype('int64')}
Column: {'LCB'} Position: {80} DataType: {dtype('int64')}
Column: {'CB'} Position: {81} DataType: {dtype('int64')}
Column: {'RCB'} Position: {82} DataType: {dtype('int64')}
Column: {'RB'} Position: {83} DataType: {dtype('int64')}
Column: {'GK'} Position: {84} DataType: {dtype('int64')}
Column: {'OVA'} Position: {85} DataType: {dtype('int64')}

In [14]:
# Column Drop Iterations

# columns_to_drop = fifa_df.columns[1:50]
# fifa_df = fifa_df.drop(columns=columns_to_drop)

# for column_name, dtype in fifa_df.dtypes.items():
#     print("Column:", {column_name}, "Data Type:", {dtype})

In [15]:
fifa_df.describe()

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
count,11701.00000,11701.000000,1.170100e+04,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,...,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000
mean,25.27049,5.534655,2.543772e+06,258.482181,51.593795,48.048116,53.494060,60.436800,45.067324,266.497222,...,56.515170,56.515170,56.959662,56.173319,54.881634,54.881634,54.881634,56.173319,22.667977,66.921972
std,4.95764,5.810903,5.267533e+06,72.267012,17.872747,19.399617,16.956195,13.971811,17.701804,76.835287,...,13.409094,13.409094,13.219660,13.534768,14.412883,14.412883,14.412883,13.534768,14.524695,6.876081
min,16.00000,-1.000000,0.000000e+00,33.000000,6.000000,3.000000,5.000000,8.000000,4.000000,43.000000,...,18.000000,18.000000,16.000000,15.000000,18.000000,18.000000,18.000000,15.000000,10.000000,38.000000
25%,21.00000,0.000000,3.750000e+05,232.000000,41.000000,33.000000,46.000000,56.000000,32.000000,232.000000,...,49.000000,49.000000,51.000000,49.000000,44.000000,44.000000,44.000000,49.000000,17.000000,62.000000
50%,25.00000,4.000000,8.000000e+05,271.000000,56.000000,52.000000,56.000000,63.000000,47.000000,279.000000,...,59.000000,59.000000,59.000000,59.000000,57.000000,57.000000,57.000000,59.000000,18.000000,67.000000
75%,29.00000,10.000000,2.400000e+06,306.000000,65.000000,64.000000,65.000000,69.000000,59.000000,319.000000,...,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,20.000000,72.000000
max,43.00000,26.000000,9.000000e+07,437.000000,94.000000,95.000000,93.000000,94.000000,90.000000,470.000000,...,89.000000,89.000000,87.000000,86.000000,89.000000,89.000000,89.000000,86.000000,91.000000,93.000000

In [16]:
y = fifa_df['OVA']
X = fifa_df.drop(['OVA'], axis=1)     

X_num = X.select_dtypes(include=np.number)
X_cat = X.select_dtypes(include=object)

X_num.describe()

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK
count,11701.00000,11701.000000,1.170100e+04,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,...,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000
mean,25.27049,5.534655,2.543772e+06,258.482181,51.593795,48.048116,53.494060,60.436800,45.067324,266.497222,...,56.515170,56.515170,56.515170,56.959662,56.173319,54.881634,54.881634,54.881634,56.173319,22.667977
std,4.95764,5.810903,5.267533e+06,72.267012,17.872747,19.399617,16.956195,13.971811,17.701804,76.835287,...,13.409094,13.409094,13.409094,13.219660,13.534768,14.412883,14.412883,14.412883,13.534768,14.524695
min,16.00000,-1.000000,0.000000e+00,33.000000,6.000000,3.000000,5.000000,8.000000,4.000000,43.000000,...,18.000000,18.000000,18.000000,16.000000,15.000000,18.000000,18.000000,18.000000,15.000000,10.000000
25%,21.00000,0.000000,3.750000e+05,232.000000,41.000000,33.000000,46.000000,56.000000,32.000000,232.000000,...,49.000000,49.000000,49.000000,51.000000,49.000000,44.000000,44.000000,44.000000,49.000000,17.000000
50%,25.00000,4.000000,8.000000e+05,271.000000,56.000000,52.000000,56.000000,63.000000,47.000000,279.000000,...,59.000000,59.000000,59.000000,59.000000,59.000000,57.000000,57.000000,57.000000,59.000000,18.000000
75%,29.00000,10.000000,2.400000e+06,306.000000,65.000000,64.000000,65.000000,69.000000,59.000000,319.000000,...,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,20.000000
max,43.00000,26.000000,9.000000e+07,437.000000,94.000000,95.000000,93.000000,94.000000,90.000000,470.000000,...,89.000000,89.000000,89.000000,87.000000,86.000000,89.000000,89.000000,89.000000,86.000000,91.000000

## Scale the data

In [17]:
# MINMAX SCALER NUMERICAL DATA

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

transformer = MinMaxScaler().fit(X_num)
x_normalized = transformer.transform(X_num)
x_normalized = pd.DataFrame(x_normalized, columns=X_num.columns)
x_normalized.head()

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK
0,0.370370,0.074074,0.005833,0.556931,0.545455,0.478261,0.431818,0.720930,0.465116,0.569087,...,0.591549,0.591549,0.591549,0.619718,0.619718,0.521127,0.521127,0.521127,0.619718,0.074074
1,0.518519,0.037037,0.094444,0.821782,0.681818,0.826087,0.806818,0.697674,0.837209,0.777518,...,0.521127,0.521127,0.521127,0.605634,0.563380,0.450704,0.450704,0.450704,0.563380,0.123457
2,0.629630,0.037037,0.100000,0.750000,0.761364,0.793478,0.329545,0.813953,0.825581,0.892272,...,0.563380,0.563380,0.563380,0.633803,0.563380,0.352113,0.352113,0.352113,0.563380,0.049383
3,0.222222,0.518519,0.003056,0.517327,0.431818,0.423913,0.602273,0.627907,0.372093,0.505855,...,0.591549,0.591549,0.591549,0.591549,0.619718,0.591549,0.591549,0.591549,0.619718,0.074074
4,0.259259,0.333333,0.008056,0.534653,0.488636,0.369565,0.636364,0.697674,0.348837,0.555035,...,0.676056,0.676056,0.676056,0.704225,0.704225,0.633803,0.633803,0.633803,0.704225,0.086420

In [18]:
# ONE HOT ENCODE CATEGORICAL DATA

from sklearn.preprocessing import OneHotEncoder

In [19]:
X_cat = ['BP', 'W/F', 'SM', 'A/W', 'D/W' , 'IR']

selected_col = fifa_df[X_cat]

encoder = OneHotEncoder(drop='first').fit(selected_col)
encoded = encoder.transform(selected_col).toarray()

X_cat_encoded = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(X_cat))

X_cat_encoded.head(20)

,BP_CB,BP_CDM,BP_CF,BP_CM,BP_GK,BP_LB,BP_LM,BP_LW,BP_LWB,BP_RB,...,SM_4★,SM_5★,A/W_Low,A/W_Medium,D/W_Low,D/W_Medium,IR_2 ★,IR_3 ★,IR_4 ★,IR_5 ★
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
8,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
9,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
10,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
12,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
14,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
19,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [20]:
X = pd.concat([x_normalized, X_cat_encoded], axis = 1)
X.describe()

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,SM_4★,SM_5★,A/W_Low,A/W_Medium,D/W_Low,D/W_Medium,IR_2 ★,IR_3 ★,IR_4 ★,IR_5 ★
count,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,...,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000
mean,0.343351,0.242024,0.028264,0.558124,0.518111,0.489653,0.551069,0.609730,0.477527,0.523413,...,0.074353,0.004017,0.051278,0.645500,0.108110,0.718657,0.086061,0.024357,0.003675,0.000598
std,0.183616,0.215219,0.058528,0.178879,0.203099,0.210865,0.192684,0.162463,0.205835,0.179942,...,0.262355,0.063253,0.220573,0.478382,0.310533,0.449674,0.280466,0.154161,0.060512,0.024453
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.185185,0.037037,0.004167,0.492574,0.397727,0.326087,0.465909,0.558140,0.325581,0.442623,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.333333,0.185185,0.008889,0.589109,0.568182,0.532609,0.579545,0.639535,0.500000,0.552693,...,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,0.481481,0.407407,0.026667,0.675743,0.670455,0.663043,0.681818,0.709302,0.639535,0.646370,...,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [21]:
# TRAIN TEST SPLIT

from sklearn.model_selection import train_test_split as tts

X_train, X_test, y_train, y_test=tts(X, y, test_size=.1)

In [22]:
X_train

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,SM_4★,SM_5★,A/W_Low,A/W_Medium,D/W_Low,D/W_Medium,IR_2 ★,IR_3 ★,IR_4 ★,IR_5 ★
9355,0.148148,0.518519,0.004167,0.448020,0.511364,0.271739,0.590909,0.511628,0.255814,0.419204,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4886,0.296296,0.185185,0.008333,0.608911,0.659091,0.597826,0.568182,0.662791,0.383721,0.538642,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
9601,0.296296,0.037037,0.048889,0.740099,0.806818,0.728261,0.568182,0.709302,0.662791,0.637002,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2054,0.259259,0.185185,0.007778,0.457921,0.409091,0.282609,0.670455,0.511628,0.313953,0.358314,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7608,0.444444,0.037037,0.061111,0.628713,0.715909,0.456522,0.704545,0.709302,0.383721,0.536300,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3560,0.444444,0.037037,0.045556,0.715347,0.352273,0.760870,0.829545,0.662791,0.755814,0.618267,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
9337,0.296296,0.222222,0.038889,0.680693,0.670455,0.510870,0.761364,0.744186,0.523256,0.625293,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6460,0.222222,0.222222,0.005278,0.564356,0.477273,0.467391,0.579545,0.697674,0.453488,0.580796,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3477,0.037037,0.666667,0.005556,0.608911,0.386364,0.619565,0.715909,0.581395,0.569767,0.451991,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
8973,0.259259,0.407407,0.043333,0.146040,0.090909,0.141304,0.170455,0.209302,0.139535,0.117096,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [23]:
y_train

9355    60
4886    66
9601    73
2054    66
7608    75
        ..
3560    73
9337    72
6460    63
3477    61
8973    72
Name: OVA, Length: 10530, dtype: int64

In [24]:
from sklearn.linear_model import LinearRegression as linreg

lm = linreg()
lm.fit(X_train,y_train)
y_pred = lm.predict(X_test)

In [25]:
from sklearn.metrics import r2_score

In [26]:
predictions = lm.predict(X_train)
r2_score(y_train, predictions)

0.9193393511625526

In [27]:
predictions_test = lm.predict(X_test)
r2_score(y_test, predictions_test)

0.9163255338884062

In [28]:
display(y_test[:5])
display(predictions_test[:5])

6837    71
519     60
9269    75
7661    68
62      63
Name: OVA, dtype: int64

array([67.95898438, 60.24023438, 74.18945312, 67.87304688, 60.30566406])

## Create GK Model

In [29]:
# This model will be based on the Best Position of GK (Goalkeeper)

In [30]:
# # Drop any irrelevant columns that is within other positions
# # Filter the BP to only have GK values

# fifa_gk = fifa_df.drop(['LS', 'ST', 'RS','LW', 'LF', 'CF', 'RF', 'RW', 'LAM','CAM', 'RAM', 'LM', 'LCM','CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB','CB', 'RCB', 'RB'], axis=1)

# fifa_gk = fifa_gk[fifa_gk['BP'] == 'GK']

# fifa_gk.shape

In [31]:
# # We still want to base the model on Overall Value

# y_gk = fifa_gk['OVA']
# X_gk = fifa_gk.drop(['OVA'], axis=1) 

# X_num_gk = X_gk.select_dtypes(include=np.number)
# X_cat_gk = X_gk.select_dtypes(include=object)

# # X_num_gk.describe()


# print(X_gk.shape)
# print(y_gk.shape)

In [32]:
# transformer_gk = MinMaxScaler().fit(X_num_gk)
# x_normalized_gk = transformer_gk.transform(X_num_gk)
# print(x_normalized_gk.shape)
# x_normalized_gk = pd.DataFrame(x_normalized_gk, columns=X_num_gk.columns)
# x_normalized_gk.head()

In [33]:
# X_gk.shape

In [34]:
# X_cat_gk = ['BP', 'W/F', 'SM', 'A/W', 'D/W' , 'IR']

# selected_col_gk = X_gk[X_cat_gk]

# encoder = OneHotEncoder(drop='first').fit(selected_col_gk)
# encoded = encoder.transform(selected_col_gk).toarray()

# X_cat_encoded_gk = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(X_cat_gk))

# X_cat_encoded_gk.head(20)

In [35]:
# X_gk = pd.concat([x_normalized_gk, X_cat_encoded_gk], axis = 1)

# X_gk.shape

# print(x_normalized_gk.shape)
# print(X_cat_encoded_gk.shape)

In [36]:
# from sklearn.model_selection import train_test_split as tts

# X_train_gk, X_test_gk, y_train_gk, y_test_gk=tts(X_gk, y_gk, test_size=.25)

In [37]:
# X_train_gk

In [38]:
# y_train_gk

In [39]:
# from sklearn.linear_model import LinearRegression as linreg

# lm_gk = linreg()
# lm_gk.fit(X_train_gk,y_train_gk)
# y_pred_gk = lm_gk.predict(X_test_gk)

In [40]:
# from sklearn.metrics import r2_score

# predictions_gk = lm_gk.predict(X_train_gk)
# r2_score(y_train_gk, predictions_gk)

In [41]:
# predictions_test_gk = lm_gk.predict(X_test_gk)
# r2_score(y_test_gk, predictions_test_gk)

In [42]:
# display(y_test_gk[:5])
# display(predictions_test_gk[:5])

## FIFA Data to Validate

In [43]:
fifa_vd = pd.read_csv('fifa21_validate.csv')

fifa_vd.shape

(1999, 101)

In [44]:
fifa_vd = fifa_vd.drop(['ID', 'Name', 'Club', 'Hits', 'Nationality', 'Position','Team & Contract','Height','Weight', 'foot','Joined','Loan Date End','Wage','Release Clause','Contract'], axis=1)

fifa_vd.columns.values

array(['Age', 'BP', 'Growth', 'Value', 'Attacking', 'Crossing',
       'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed',
       'Agility', 'Reactions', 'Balance', 'Power', 'Shot Power',
       'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Mentality',
       'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking',
       'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'GK Diving',
       'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes',
       'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR',
       'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'LS', 'ST', 'RS', 'LW',
       'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM',
       'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
       'RCB', 'RB', 'GK', 'OVA'], dtype=object)

In [45]:
# drop duplicates

fifa_vd.drop_duplicates()

,Age,BP,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,23,CB,7,€975K,230,47,21,62,60,40.0,...,61+2,61+2,59+2,61+2,67+2,67+2,67+2,61+2,16+2,67
1,22,CAM,5,€1.2M,298,62,60,44,62,70.0,...,47+2,47+2,49+2,45+2,38+2,38+2,38+2,45+2,17+2,68
2,19,GK,17,€120K,48,7,5,11,21,4.0,...,18+2,18+2,16+2,16+2,18+2,18+2,18+2,16+2,53+2,54
3,16,CDM,23,€160K,215,38,31,55,59,32.0,...,54+2,54+2,53+2,53+2,54+2,54+2,54+2,53+2,11+2,55
4,24,CDM,5,€2.3M,295,57,59,45,78,56.0,...,72+2,72+2,70+2,69+2,68+2,68+2,68+2,69+2,18+2,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,21,LB,11,€325K,197,59,23,42,51,22.0,...,52+2,52+2,58+2,58+2,54+2,54+2,54+2,58+2,15+2,60
1995,21,GK,9,€190K,77,13,9,14,34,7.0,...,23+2,23+2,20+2,20+2,22+2,22+2,22+2,20+2,58+2,59
1996,27,RM,0,€8M,332,76,72,34,79,71.0,...,60+2,60+2,62+2,57+2,47+2,47+2,47+2,57+2,18+2,76
1997,34,CDM,0,€140K,268,58,44,61,62,43.0,...,62+1,62+1,60+2,60+2,63+0,63+0,63+0,60+2,14+2,63
1998,18,CAM,16,€425K,276,49,54,51,70,52.0,...,55+2,55+2,55+2,54+2,51+2,51+2,51+2,54+2,16+2,60

In [46]:
fifa_vd.columns[fifa_vd.isna().any()].tolist()

['Volleys',
 'Curve',
 'Agility',
 'Balance',
 'Jumping',
 'Vision',
 'Composure',
 'Sliding Tackle',
 'A/W',
 'D/W']

In [47]:
volleys_mean_vd = fifa_vd['Volleys'].mean()
curve_mean_vd = fifa_vd['Curve'].mean()
agility_mean_vd = fifa_vd['Agility'].mean()
balance_mean_vd = fifa_vd['Balance'].mean()
jumping_mean_vd = fifa_vd['Jumping'].mean()
visions_mean_vd = fifa_vd['Vision'].mean()
composure_mean_vd = fifa_vd['Composure'].mean()
sliding_mean_vd = fifa_vd['Sliding Tackle'].mean()
aw_mode_vd = fifa_vd['A/W'].mode()[0]
dw_mode_vd = fifa_vd['D/W'].mode()[0]


fifa_vd['Volleys'].fillna(volleys_mean_vd, inplace=True)
fifa_vd['Curve'].fillna(curve_mean_vd, inplace=True)
fifa_vd['Agility'].fillna(agility_mean_vd, inplace=True)
fifa_vd['Balance'].fillna(balance_mean_vd, inplace=True)
fifa_vd['Jumping'].fillna(jumping_mean_vd, inplace=True)
fifa_vd['Vision'].fillna(visions_mean_vd, inplace=True)
fifa_vd['Composure'].fillna(composure_mean_vd, inplace=True)
fifa_vd['Sliding Tackle'].fillna(sliding_mean_vd, inplace=True)
fifa_vd['A/W'].fillna(aw_mode_vd, inplace=True)
fifa_vd['D/W'].fillna(dw_mode_vd, inplace=True)

# check again for any NaN values

fifa_vd.columns[fifa_vd.isna().any()].tolist()

[]

In [48]:
def sum_values(value_str):
    values = value_str.split('+')
    return sum(map(int, values))

columns_to_change = ['LS', 'ST', 'RS','LW', 'LF', 'CF', 'RF', 'RW', 'LAM','CAM', 'RAM', 'LM', 'LCM','CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB','CB', 'RCB', 'RB', 'GK']

fifa_vd[columns_to_change] = fifa_vd[columns_to_change].applymap(sum_values)
fifa_vd[columns_to_change] = fifa_vd[columns_to_change].astype(int)

In [49]:
def convert_currency (value):
    if 'K' in value:
        return float(value.replace('€', '').replace('K', '')) * 1000
    elif 'M' in value:
        return float(value.replace('€', '').replace('M', '')) * 1000000
    else:
        return float(value.replace('€', ''))
    
fifa_vd['Value'] = fifa_vd['Value'].apply(convert_currency)

print(fifa_vd['Value'])

0        975000.0
1       1200000.0
2        120000.0
3        160000.0
4       2300000.0
          ...
1994     325000.0
1995     190000.0
1996    8000000.0
1997     140000.0
1998     425000.0
Name: Value, Length: 1999, dtype: float64

In [50]:
fifa_vd.head()

,Age,BP,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,23,CB,7,975000.0,230,47,21,62,60,40.0,...,63,63,61,63,69,69,69,63,18,67
1,22,CAM,5,1200000.0,298,62,60,44,62,70.0,...,49,49,51,47,40,40,40,47,19,68
2,19,GK,17,120000.0,48,7,5,11,21,4.0,...,20,20,18,18,20,20,20,18,55,54
3,16,CDM,23,160000.0,215,38,31,55,59,32.0,...,56,56,55,55,56,56,56,55,13,55
4,24,CDM,5,2300000.0,295,57,59,45,78,56.0,...,74,74,72,71,70,70,70,71,20,70

In [51]:
# X-y Split

y_vd = fifa_vd['OVA']
X_vd = fifa_vd.drop(['OVA'], axis=1)     

X_num_vd = X_vd.select_dtypes(include=np.number)
X_cat_vd = X_vd.select_dtypes(include=object)

X_num_vd.describe()

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK
count,1999.000000,1999.000000,1.999000e+03,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,...,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000
mean,25.377189,5.365183,2.583663e+06,257.325663,51.538769,47.697349,53.262631,60.376188,44.517535,265.714357,...,56.698349,56.698349,56.698349,57.097549,56.369685,55.133567,55.133567,55.133567,56.369685,23.062531
std,4.867082,5.715451,5.451206e+06,73.267951,18.062659,19.483289,17.328469,14.001378,17.907565,78.394468,...,13.571837,13.571837,13.571837,13.415102,13.724112,14.569658,14.569658,14.569658,13.724112,15.211673
min,16.000000,0.000000,0.000000e+00,48.000000,6.000000,4.000000,8.000000,11.000000,4.000000,52.000000,...,19.000000,19.000000,19.000000,17.000000,17.000000,19.000000,19.000000,19.000000,17.000000,10.000000
25%,21.500000,0.000000,3.750000e+05,230.000000,40.500000,32.000000,45.000000,56.000000,32.000000,230.000000,...,49.000000,49.000000,49.000000,52.000000,50.000000,45.000000,45.000000,45.000000,50.000000,17.000000
50%,25.000000,4.000000,8.000000e+05,271.000000,56.000000,52.000000,56.000000,63.000000,46.000000,278.000000,...,59.000000,59.000000,59.000000,60.000000,59.000000,58.000000,58.000000,58.000000,59.000000,18.000000
75%,29.000000,9.000000,2.400000e+06,305.000000,65.000000,64.000000,65.000000,70.000000,58.000000,319.000000,...,67.000000,67.000000,67.000000,66.000000,66.000000,67.000000,67.000000,67.000000,66.000000,20.000000
max,47.000000,25.000000,7.800000e+07,405.000000,89.000000,91.000000,93.000000,92.000000,85.000000,432.000000,...,88.000000,88.000000,88.000000,85.000000,85.000000,87.000000,87.000000,87.000000,85.000000,92.000000

In [52]:
# Normalize MinMax

x_normalized_vd = transformer.transform(X_num_vd)
x_normalized_vd = pd.DataFrame(x_normalized_vd,columns=X_num_vd.columns)
print(x_normalized_vd.shape)

(1999, 79)

In [53]:
# OneHot Encoded

X_cat_vd = ['BP', 'W/F', 'SM', 'A/W', 'D/W' , 'IR']
selected_col_vd = fifa_vd[X_cat_vd]
encoder = OneHotEncoder(drop='first').fit(selected_col_vd)
encoded2 = encoder.transform(selected_col_vd).toarray()
X_cat_encoded_vd = pd.DataFrame(encoded2, columns=encoder.get_feature_names_out(X_cat_vd))
X_cat_encoded_vd.head(20)


# encoded2 = encoder.transform(X_cat_vd).toarray()
# print(encoded2)

# X_cat_encoded_vd = pd.DataFrame(encoded2)
# X_cat_encoded_vd.head(30)

,BP_CB,BP_CDM,BP_CF,BP_CM,BP_GK,BP_LB,BP_LM,BP_LW,BP_LWB,BP_RB,...,SM_3★,SM_4★,SM_5★,A/W_Low,A/W_Medium,D/W_Low,D/W_Medium,IR_2 ★,IR_3 ★,IR_4 ★
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
10,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
11,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
12,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
13,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
15,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
19,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [54]:
# Concat

X_vd = pd.concat([x_normalized_vd, X_cat_encoded_vd], axis = 1)

X_vd.shape

print(x_normalized_vd.shape)
print(X_cat_encoded_vd.shape)

(1999, 79)
(1999, 29)

In [55]:
from sklearn.model_selection import train_test_split as tts

X_train_vd, X_test_vd, y_train_vd, y_test_vd=tts(X_vd, y_vd, test_size=.2)

In [56]:
lm_vd = linreg()
lm_vd.fit(X_train_vd,y_train_vd)
y_pred_vd = lm_vd.predict(X_test_vd)

In [57]:
predictions_vd = lm_vd.predict(X_train_vd)
r2_score(y_train_vd, predictions_vd)

0.8925243079298854

In [58]:
predictions_test_vd = lm_vd.predict(X_test_vd)
r2_score(y_test_vd, predictions_test_vd)

0.8690759723799026

In [59]:
display(y_test_vd[:5])
display(predictions_test_vd[:5])

1581    70
512     60
230     54
193     71
429     69
Name: OVA, dtype: int64

array([66.03125  , 57.7734375, 58.203125 , 71.015625 , 67.09375  ])

In [60]:
from sklearn.metrics import mean_absolute_error as mae

train_mae=mae(lm_vd.predict(X_train_vd), y_train_vd)
test_mae=mae(y_pred_vd, y_test_vd)

print ('train MAE: {} -- test MAE: {}'.format(train_mae, test_mae))

train MAE: 1.6897865853658536 -- test MAE: 1.92880859375

In [61]:
from sklearn.metrics import mean_squared_error as mse


train_mse=mse(lm.predict(X_train), y_train)
test_mse=mse(y_pred, y_test)

print ('train MSE: {} -- test MSE: {}'.format(train_mse, test_mse))

train MSE: 3.835214781783811 -- test MSE: 3.742649523851507

In [62]:
print ('train RMSE: {} -- test RMSE: {}'.format(train_mse**.5, test_mse**.5))

train RMSE: 1.9583704403875717 -- test RMSE: 1.9345928573866666