In [1]:
import pandas as pd
import numpy as np
import math

import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

fifa_df = pd.read_csv('fifa21_train.csv')

fifa_df.shape

(11701, 101)

In [2]:
fifa_df.columns.values

array(['ID', 'Name', 'Age', 'Nationality', 'Club', 'BP', 'Position',
       'Team & Contract', 'Height', 'Weight', 'foot', 'Growth', 'Joined',
       'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Contract',
       'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy',
       'Short Passing', 'Volleys', 'Skill', 'Dribbling', 'Curve',
       'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength',
       'Long Shots', 'Mentality', 'Aggression', 'Interceptions',
       'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W',
       'D/W', 'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits',
       'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM',
       'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM',
       'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'GK', 'OVA'], dtype=object)

In [3]:
fifa_df = fifa_df.drop(['ID', 'Name', 'Club', 'Hits', 'Nationality', 'Position','Team & Contract','Height','Weight', 'foot','Joined','Loan Date End','Wage','Release Clause','Contract'], axis=1)

fifa_df.columns.values

array(['Age', 'BP', 'Growth', 'Value', 'Attacking', 'Crossing',
       'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed',
       'Agility', 'Reactions', 'Balance', 'Power', 'Shot Power',
       'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Mentality',
       'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking',
       'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'GK Diving',
       'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes',
       'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR',
       'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'LS', 'ST', 'RS', 'LW',
       'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM',
       'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
       'RCB', 'RB', 'GK', 'OVA'], dtype=object)

In [4]:
# drop duplicates

fifa_df.drop_duplicates()

,Age,BP,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,26,CM,1,€525K,258,54,47,43,70,44.0,...,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,30,ST,0,€8.5M,365,66,79,76,68,76.0,...,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,33,CAM,0,€9M,336,73,76,34,78,75.0,...,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,22,CDM,13,€275K,242,44,42,58,62,36.0,...,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,23,CDM,8,€725K,249,49,37,61,68,34.0,...,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,25,LB,5,€625K,224,62,24,51,59,28.0,...,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2,65
11697,27,GK,4,€1.6M,84,12,14,13,29,16.0,...,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2,70
11698,22,RM,8,€1.1M,286,64,66,51,64,41.0,...,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2,67
11699,26,CM,7,€0,254,64,66,51,73,NaN,...,68+0,68+0,66+0,64+0,60+0,60+0,60+0,64+0,25+0,68
11700,22,CAM,9,€700K,289,43,64,65,64,53.0,...,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2,64

In [5]:
# nan_positions_tuples = list(zip(*np.where(fifa_df.isna())))
# print(nan_positions_tuples)

fifa_df.columns[fifa_df.isna().any()].tolist()

['Volleys',
 'Curve',
 'Agility',
 'Balance',
 'Jumping',
 'Interceptions',
 'Positioning',
 'Vision',
 'Composure',
 'Sliding Tackle',
 'A/W',
 'D/W']

In [6]:
# filling NaN values with mean and mode

volleys_mean = fifa_df['Volleys'].mean()
curve_mean = fifa_df['Curve'].mean()
agility_mean = fifa_df['Agility'].mean()
balance_mean = fifa_df['Balance'].mean()
jumping_mean = fifa_df['Jumping'].mean()
interceptions_mean = fifa_df['Interceptions'].mean()
positioning_mean = fifa_df['Positioning'].mean()
visions_mean = fifa_df['Vision'].mean()
composure_mean = fifa_df['Composure'].mean()
sliding_mean = fifa_df['Sliding Tackle'].mean()
aw_mode = fifa_df['A/W'].mode()[0]
dw_mode = fifa_df['D/W'].mode()[0]


fifa_df['Volleys'].fillna(volleys_mean, inplace=True)
fifa_df['Curve'].fillna(curve_mean, inplace=True)
fifa_df['Agility'].fillna(agility_mean, inplace=True)
fifa_df['Balance'].fillna(balance_mean, inplace=True)
fifa_df['Jumping'].fillna(jumping_mean, inplace=True)
fifa_df['Interceptions'].fillna(interceptions_mean, inplace=True)
fifa_df['Positioning'].fillna(positioning_mean, inplace=True)
fifa_df['Vision'].fillna(visions_mean, inplace=True)
fifa_df['Composure'].fillna(composure_mean, inplace=True)
fifa_df['Sliding Tackle'].fillna(sliding_mean, inplace=True)
fifa_df['A/W'].fillna(aw_mode, inplace=True)
fifa_df['D/W'].fillna(dw_mode, inplace=True)

# check again for any NaN values

fifa_df.columns[fifa_df.isna().any()].tolist()

[]

In [7]:
# replace ★ values within columns

fifa_df['W/F'].str.replace('★', '')
fifa_df['SM'].str.replace('★', '')
fifa_df['IR'].str.replace('★', '')

0        1
1        2
2        2
3        1
4        1
         ..
11696    1
11697    1
11698    1
11699    3
11700    1
Name: IR, Length: 11701, dtype: object

In [8]:
def sum_values(value_str):
    values = value_str.split('+')
    return sum(map(int, values))

columns_to_change = ['LS', 'ST', 'RS','LW', 'LF', 'CF', 'RF', 'RW', 'LAM','CAM', 'RAM', 'LM', 'LCM','CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB','CB', 'RCB', 'RB', 'GK']

fifa_df[columns_to_change] = fifa_df[columns_to_change].applymap(sum_values)
fifa_df[columns_to_change] = fifa_df[columns_to_change].astype(int)

In [9]:
def convert_currency (value):
    if 'K' in value:
        return float(value.replace('€', '').replace('K', '')) * 1000
    elif 'M' in value:
        return float(value.replace('€', '').replace('M', '')) * 1000000
    else:
        return float(value.replace('€', ''))
    
fifa_df['Value'] = fifa_df['Value'].apply(convert_currency)

print(fifa_df['Value'])

0         525000.0
1        8500000.0
2        9000000.0
3         275000.0
4         725000.0
           ...
11696     625000.0
11697    1600000.0
11698    1100000.0
11699          0.0
11700     700000.0
Name: Value, Length: 11701, dtype: float64

In [10]:
fifa_df.shape

(11701, 86)

In [11]:
fifa_df['BP'] = fifa_df['BP'].replace({'RB':'DEF', 'LB':'DEF', 'CB':'DEF', 'LWB' : 'DEF', 'RWB':'DEF'})
fifa_df['BP'] = fifa_df['BP'].replace({'RW':'MID', 'LW':'MID', 'RM':'MID', 'LM' : 'MID', 'CDM':'MID', 'CAM':'MID','CM':'MID'})
fifa_df['BP'] = fifa_df['BP'].replace({'ST': 'FWD', 'CF': 'FWD'})

In [12]:
for column_name, dtype in fifa_df.dtypes.items():
    print("Column:", {column_name}, "Data Type:", {dtype})

Column: {'Age'} Data Type: {dtype('int64')}
Column: {'BP'} Data Type: {dtype('O')}
Column: {'Growth'} Data Type: {dtype('int64')}
Column: {'Value'} Data Type: {dtype('float64')}
Column: {'Attacking'} Data Type: {dtype('int64')}
Column: {'Crossing'} Data Type: {dtype('int64')}
Column: {'Finishing'} Data Type: {dtype('int64')}
Column: {'Heading Accuracy'} Data Type: {dtype('int64')}
Column: {'Short Passing'} Data Type: {dtype('int64')}
Column: {'Volleys'} Data Type: {dtype('float64')}
Column: {'Skill'} Data Type: {dtype('int64')}
Column: {'Dribbling'} Data Type: {dtype('int64')}
Column: {'Curve'} Data Type: {dtype('float64')}
Column: {'FK Accuracy'} Data Type: {dtype('int64')}
Column: {'Long Passing'} Data Type: {dtype('int64')}
Column: {'Ball Control'} Data Type: {dtype('int64')}
Column: {'Movement'} Data Type: {dtype('int64')}
Column: {'Acceleration'} Data Type: {dtype('int64')}
Column: {'Sprint Speed'} Data Type: {dtype('int64')}
Column: {'Agility'} Data Type: {dtype('float64')}
Column: {'Reactions'} Data Type: {dtype('int64')}
Column: {'Balance'} Data Type: {dtype('float64')}
Column: {'Power'} Data Type: {dtype('int64')}
Column: {'Shot Power'} Data Type: {dtype('int64')}
Column: {'Jumping'} Data Type: {dtype('float64')}
Column: {'Stamina'} Data Type: {dtype('int64')}
Column: {'Strength'} Data Type: {dtype('int64')}
Column: {'Long Shots'} Data Type: {dtype('int64')}
Column: {'Mentality'} Data Type: {dtype('int64')}
Column: {'Aggression'} Data Type: {dtype('int64')}
Column: {'Interceptions'} Data Type: {dtype('float64')}
Column: {'Positioning'} Data Type: {dtype('float64')}
Column: {'Vision'} Data Type: {dtype('float64')}
Column: {'Penalties'} Data Type: {dtype('int64')}
Column: {'Composure'} Data Type: {dtype('float64')}
Column: {'Defending'} Data Type: {dtype('int64')}
Column: {'Marking'} Data Type: {dtype('int64')}
Column: {'Standing Tackle'} Data Type: {dtype('int64')}
Column: {'Sliding Tackle'} Data Type: {dtype('float64')}
Column: {'Goalkeeping'} Data Type: {dtype('int64')}
Column: {'GK Diving'} Data Type: {dtype('int64')}
Column: {'GK Handling'} Data Type: {dtype('int64')}
Column: {'GK Kicking'} Data Type: {dtype('int64')}
Column: {'GK Positioning'} Data Type: {dtype('int64')}
Column: {'GK Reflexes'} Data Type: {dtype('int64')}
Column: {'Total Stats'} Data Type: {dtype('int64')}
Column: {'Base Stats'} Data Type: {dtype('int64')}
Column: {'W/F'} Data Type: {dtype('O')}
Column: {'SM'} Data Type: {dtype('O')}
Column: {'A/W'} Data Type: {dtype('O')}
Column: {'D/W'} Data Type: {dtype('O')}
Column: {'IR'} Data Type: {dtype('O')}
Column: {'PAC'} Data Type: {dtype('int64')}
Column: {'SHO'} Data Type: {dtype('int64')}
Column: {'PAS'} Data Type: {dtype('int64')}
Column: {'DRI'} Data Type: {dtype('int64')}
Column: {'DEF'} Data Type: {dtype('int64')}
Column: {'PHY'} Data Type: {dtype('int64')}
Column: {'LS'} Data Type: {dtype('int64')}
Column: {'ST'} Data Type: {dtype('int64')}
Column: {'RS'} Data Type: {dtype('int64')}
Column: {'LW'} Data Type: {dtype('int64')}
Column: {'LF'} Data Type: {dtype('int64')}
Column: {'CF'} Data Type: {dtype('int64')}
Column: {'RF'} Data Type: {dtype('int64')}
Column: {'RW'} Data Type: {dtype('int64')}
Column: {'LAM'} Data Type: {dtype('int64')}
Column: {'CAM'} Data Type: {dtype('int64')}
Column: {'RAM'} Data Type: {dtype('int64')}
Column: {'LM'} Data Type: {dtype('int64')}
Column: {'LCM'} Data Type: {dtype('int64')}
Column: {'CM'} Data Type: {dtype('int64')}
Column: {'RCM'} Data Type: {dtype('int64')}
Column: {'RM'} Data Type: {dtype('int64')}
Column: {'LWB'} Data Type: {dtype('int64')}
Column: {'LDM'} Data Type: {dtype('int64')}
Column: {'CDM'} Data Type: {dtype('int64')}
Column: {'RDM'} Data Type: {dtype('int64')}
Column: {'RWB'} Data Type: {dtype('int64')}
Column: {'LB'} Data Type: {dtype('int64')}
Column: {'LCB'} Data Type: {dtype('int64')}
Column: {'CB'} Data Type: {dtype('int64')}
Column: {'RCB'} Data Type: {dtype('int64')}
Column: {'RB'} Data Type: {dtype('int64')}
Column: {'GK'} Data Type: {dtype('int64')}
Column: {'OVA'} Data Type: {dtype('int64')}

In [13]:
fifa_df.describe()

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
count,11701.00000,11701.000000,1.170100e+04,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,...,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000
mean,25.27049,5.534655,2.543772e+06,258.482181,51.593795,48.048116,53.494060,60.436800,45.067324,266.497222,...,56.515170,56.515170,56.959662,56.173319,54.881634,54.881634,54.881634,56.173319,22.667977,66.921972
std,4.95764,5.810903,5.267533e+06,72.267012,17.872747,19.399617,16.956195,13.971811,17.701804,76.835287,...,13.409094,13.409094,13.219660,13.534768,14.412883,14.412883,14.412883,13.534768,14.524695,6.876081
min,16.00000,-1.000000,0.000000e+00,33.000000,6.000000,3.000000,5.000000,8.000000,4.000000,43.000000,...,18.000000,18.000000,16.000000,15.000000,18.000000,18.000000,18.000000,15.000000,10.000000,38.000000
25%,21.00000,0.000000,3.750000e+05,232.000000,41.000000,33.000000,46.000000,56.000000,32.000000,232.000000,...,49.000000,49.000000,51.000000,49.000000,44.000000,44.000000,44.000000,49.000000,17.000000,62.000000
50%,25.00000,4.000000,8.000000e+05,271.000000,56.000000,52.000000,56.000000,63.000000,47.000000,279.000000,...,59.000000,59.000000,59.000000,59.000000,57.000000,57.000000,57.000000,59.000000,18.000000,67.000000
75%,29.00000,10.000000,2.400000e+06,306.000000,65.000000,64.000000,65.000000,69.000000,59.000000,319.000000,...,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,20.000000,72.000000
max,43.00000,26.000000,9.000000e+07,437.000000,94.000000,95.000000,93.000000,94.000000,90.000000,470.000000,...,89.000000,89.000000,87.000000,86.000000,89.000000,89.000000,89.000000,86.000000,91.000000,93.000000

In [14]:
y = fifa_df['OVA']
X = fifa_df.drop(['OVA'], axis=1)     

X_num = X.select_dtypes(include=np.number)
X_cat = X.select_dtypes(include=object)

X_num.describe()

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK
count,11701.00000,11701.000000,1.170100e+04,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,...,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000
mean,25.27049,5.534655,2.543772e+06,258.482181,51.593795,48.048116,53.494060,60.436800,45.067324,266.497222,...,56.515170,56.515170,56.515170,56.959662,56.173319,54.881634,54.881634,54.881634,56.173319,22.667977
std,4.95764,5.810903,5.267533e+06,72.267012,17.872747,19.399617,16.956195,13.971811,17.701804,76.835287,...,13.409094,13.409094,13.409094,13.219660,13.534768,14.412883,14.412883,14.412883,13.534768,14.524695
min,16.00000,-1.000000,0.000000e+00,33.000000,6.000000,3.000000,5.000000,8.000000,4.000000,43.000000,...,18.000000,18.000000,18.000000,16.000000,15.000000,18.000000,18.000000,18.000000,15.000000,10.000000
25%,21.00000,0.000000,3.750000e+05,232.000000,41.000000,33.000000,46.000000,56.000000,32.000000,232.000000,...,49.000000,49.000000,49.000000,51.000000,49.000000,44.000000,44.000000,44.000000,49.000000,17.000000
50%,25.00000,4.000000,8.000000e+05,271.000000,56.000000,52.000000,56.000000,63.000000,47.000000,279.000000,...,59.000000,59.000000,59.000000,59.000000,59.000000,57.000000,57.000000,57.000000,59.000000,18.000000
75%,29.00000,10.000000,2.400000e+06,306.000000,65.000000,64.000000,65.000000,69.000000,59.000000,319.000000,...,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,20.000000
max,43.00000,26.000000,9.000000e+07,437.000000,94.000000,95.000000,93.000000,94.000000,90.000000,470.000000,...,89.000000,89.000000,89.000000,87.000000,86.000000,89.000000,89.000000,89.000000,86.000000,91.000000

In [15]:
# X_num = fifa_df.drop(['OVA'], axis=1)

In [16]:
# MINMAX SCALER NUMERICAL DATA

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

transformer = MinMaxScaler().fit(X_num)
x_normalized = transformer.transform(X_num)
print(x_normalized.shape)
x_normalized = pd.DataFrame(x_normalized, columns=X_num.columns)
x_normalized.head()

(11701, 79)

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK
0,0.370370,0.074074,0.005833,0.556931,0.545455,0.478261,0.431818,0.720930,0.465116,0.569087,...,0.591549,0.591549,0.591549,0.619718,0.619718,0.521127,0.521127,0.521127,0.619718,0.074074
1,0.518519,0.037037,0.094444,0.821782,0.681818,0.826087,0.806818,0.697674,0.837209,0.777518,...,0.521127,0.521127,0.521127,0.605634,0.563380,0.450704,0.450704,0.450704,0.563380,0.123457
2,0.629630,0.037037,0.100000,0.750000,0.761364,0.793478,0.329545,0.813953,0.825581,0.892272,...,0.563380,0.563380,0.563380,0.633803,0.563380,0.352113,0.352113,0.352113,0.563380,0.049383
3,0.222222,0.518519,0.003056,0.517327,0.431818,0.423913,0.602273,0.627907,0.372093,0.505855,...,0.591549,0.591549,0.591549,0.591549,0.619718,0.591549,0.591549,0.591549,0.619718,0.074074
4,0.259259,0.333333,0.008056,0.534653,0.488636,0.369565,0.636364,0.697674,0.348837,0.555035,...,0.676056,0.676056,0.676056,0.704225,0.704225,0.633803,0.633803,0.633803,0.704225,0.086420

In [17]:
# ONE HOT ENCODE CATEGORICAL DATA

from sklearn.preprocessing import OneHotEncoder

In [18]:
X_cat = ['BP', 'W/F', 'SM', 'A/W', 'D/W' , 'IR']

selected_col = fifa_df[X_cat]

encoder = OneHotEncoder(drop='first').fit(selected_col)
encoded = encoder.transform(selected_col).toarray()

X_cat_encoded = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(X_cat))

X_cat_encoded.head(20)

,BP_FWD,BP_GK,BP_MID,W/F_2 ★,W/F_3 ★,W/F_4 ★,W/F_5 ★,SM_2★,SM_3★,SM_4★,SM_5★,A/W_Low,A/W_Medium,D/W_Low,D/W_Medium,IR_2 ★,IR_3 ★,IR_4 ★,IR_5 ★
0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
5,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
7,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
11,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
15,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
16,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
17,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
18,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [19]:
X = pd.concat([x_normalized, X_cat_encoded], axis = 1)
X.describe()

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,SM_4★,SM_5★,A/W_Low,A/W_Medium,D/W_Low,D/W_Medium,IR_2 ★,IR_3 ★,IR_4 ★,IR_5 ★
count,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,...,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000,11701.000000
mean,0.343351,0.242024,0.028264,0.558124,0.518111,0.489653,0.551069,0.609730,0.477527,0.523413,...,0.074353,0.004017,0.051278,0.645500,0.108110,0.718657,0.086061,0.024357,0.003675,0.000598
std,0.183616,0.215219,0.058528,0.178879,0.203099,0.210865,0.192684,0.162463,0.205835,0.179942,...,0.262355,0.063253,0.220573,0.478382,0.310533,0.449674,0.280466,0.154161,0.060512,0.024453
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.185185,0.037037,0.004167,0.492574,0.397727,0.326087,0.465909,0.558140,0.325581,0.442623,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.333333,0.185185,0.008889,0.589109,0.568182,0.532609,0.579545,0.639535,0.500000,0.552693,...,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,0.481481,0.407407,0.026667,0.675743,0.670455,0.663043,0.681818,0.709302,0.639535,0.646370,...,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [20]:
# TRAIN TEST SPLIT

from sklearn.model_selection import train_test_split as tts

X_train, X_test, y_train, y_test=tts(X, y, test_size=.1)

In [21]:
X_train

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,SM_4★,SM_5★,A/W_Low,A/W_Medium,D/W_Low,D/W_Medium,IR_2 ★,IR_3 ★,IR_4 ★,IR_5 ★
10886,0.185185,0.333333,0.038889,0.655941,0.738636,0.576087,0.500000,0.732558,0.546512,0.702576,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3868,0.222222,0.296296,0.010556,0.571782,0.772727,0.456522,0.500000,0.651163,0.325581,0.480094,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9094,0.074074,0.666667,0.013333,0.589109,0.659091,0.554348,0.636364,0.616279,0.313953,0.543326,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2338,0.148148,0.481481,0.004167,0.589109,0.636364,0.586957,0.500000,0.627907,0.430233,0.548009,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4708,0.296296,0.222222,0.011111,0.646040,0.556818,0.739130,0.534091,0.651163,0.558140,0.583138,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5703,0.333333,0.148148,0.025556,0.764851,0.613636,0.728261,0.852273,0.651163,0.744186,0.564403,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
7627,0.296296,0.259259,0.020000,0.054455,0.045455,0.043478,0.079545,0.151163,0.011628,0.074941,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
6999,0.444444,0.037037,0.100000,0.809406,0.772727,0.695652,0.670455,0.860465,0.802326,0.819672,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
6601,0.481481,0.037037,0.000000,0.633663,0.511364,0.652174,0.693182,0.651163,0.476744,0.517564,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5878,0.148148,0.518519,0.006111,0.396040,0.261364,0.141304,0.636364,0.593023,0.279070,0.297424,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
y_train

10886    71
3868     67
9094     66
2338     60
4708     67
         ..
5703     70
7627     70
6999     77
6601     65
5878     62
Name: OVA, Length: 10530, dtype: int64

In [23]:
from sklearn.linear_model import LinearRegression as linreg

lm = linreg()
lm.fit(X_train,y_train)
y_pred = lm.predict(X_test)

In [24]:
from sklearn.metrics import r2_score

In [25]:
predictions_test = lm.predict(X_test)
r2_score(y_test, predictions_test)

0.9141081085059191

In [26]:
predictions = lm.predict(X_train)
r2_score(y_train, predictions)

0.9164260925453198

In [27]:
display(y_test[:5])
display(predictions_test[:5])

11694    75
10117    77
9704     69
383      78
4212     67
Name: OVA, dtype: int64

array([75.01416016, 74.14794922, 70.70117188, 76.93505859, 67.34960938])

In [ ]:
# CREATE ANOTHER MODEL
# This model will be based on the Best Position of GK (Goalkeeper)

In [28]:
# Drop any irrelevant columns that is within other positions
# Filter the BP to only have GK values

fifa_gk = fifa_df.drop(['LS', 'ST', 'RS','LW', 'LF', 'CF', 'RF', 'RW', 'LAM','CAM', 'RAM', 'LM', 'LCM','CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB','CB', 'RCB', 'RB'], axis=1)

fifa_gk = fifa_gk[fifa_gk['BP'] == 'GK']

fifa_gk.shape

(1081, 60)

In [29]:
# We still want to base the model on Overall Value

y_gk = fifa_gk['OVA']
X_gk = fifa_gk.drop(['OVA'], axis=1) 

X_num_gk = X_gk.select_dtypes(include=np.number)
X_cat_gk = X_gk.select_dtypes(include=object)

# X_num_gk.describe()


print(X_gk.shape)
print(y_gk.shape)

(1081, 59)
(1081,)

In [30]:
transformer_gk = MinMaxScaler().fit(X_num_gk)
x_normalized_gk = transformer_gk.transform(X_num_gk)
print(x_normalized_gk.shape)
x_normalized_gk = pd.DataFrame(x_normalized_gk, columns=X_num_gk.columns)
x_normalized_gk.head()

(1081, 53)

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY,GK
0,0.444444,0.083333,0.004676,0.623853,0.448276,0.52,0.309524,0.377358,0.389604,0.248555,...,0.478261,0.443350,0.448980,0.391304,0.404255,0.415094,0.478261,0.679245,0.425926,0.413043
1,0.185185,0.333333,0.005036,0.211009,0.206897,0.20,0.095238,0.245283,0.048701,0.208092,...,0.304348,0.192118,0.375510,0.478261,0.553191,0.433962,0.304348,0.301887,0.388889,0.391304
2,0.296296,0.291667,0.015827,0.522936,0.241379,0.48,0.214286,0.396226,0.365254,0.300578,...,0.608696,0.577586,0.571429,0.565217,0.531915,0.584906,0.608696,0.603774,0.518519,0.543478
3,0.259259,0.416667,0.006835,0.220183,0.137931,0.24,0.142857,0.188679,0.121751,0.161850,...,0.456522,0.224138,0.408163,0.413043,0.553191,0.490566,0.456522,0.245283,0.462963,0.413043
4,0.333333,0.208333,0.064748,0.559633,0.379310,0.56,0.333333,0.301887,0.316553,0.289017,...,0.760870,0.544335,0.710204,0.673913,0.638298,0.641509,0.760870,0.716981,0.666667,0.652174

In [31]:
X_gk.shape

(1081, 59)

In [32]:
X_cat_gk = ['BP', 'W/F', 'SM', 'A/W', 'D/W' , 'IR']

selected_col_gk = X_gk[X_cat_gk]

encoder = OneHotEncoder(drop='first').fit(selected_col_gk)
encoded = encoder.transform(selected_col_gk).toarray()

X_cat_encoded_gk = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(X_cat_gk))

X_cat_encoded_gk.head(20)

    W/F_2 ★  W/F_3 ★  W/F_4 ★  W/F_5 ★  IR_2 ★  IR_3 ★  IR_4 ★
0       0.0      1.0      0.0      0.0     0.0     0.0     0.0
1       0.0      1.0      0.0      0.0     0.0     0.0     0.0
2       0.0      1.0      0.0      0.0     0.0     0.0     0.0
3       0.0      1.0      0.0      0.0     0.0     0.0     0.0
4       1.0      0.0      0.0      0.0     0.0     0.0     0.0
5       1.0      0.0      0.0      0.0     0.0     0.0     0.0
6       0.0      1.0      0.0      0.0     0.0     0.0     0.0
7       0.0      0.0      0.0      0.0     0.0     0.0     0.0
8       0.0      1.0      0.0      0.0     0.0     1.0     0.0
9       0.0      1.0      0.0      0.0     0.0     0.0     0.0
10      0.0      1.0      0.0      0.0     0.0     0.0     0.0
11      0.0      1.0      0.0      0.0     0.0     0.0     0.0
12      0.0      1.0      0.0      0.0     0.0     0.0     0.0
13      1.0      0.0      0.0      0.0     0.0     0.0     0.0
14      0.0      0.0      0.0      0.0     0.0     0.0     0.0
15      0.0      1.0      0.0      0.0     1.0     0.0     0.0
16      0.0      1.0      0.0      0.0     0.0     0.0     0.0
17      1.0      0.0      0.0      0.0     0.0     0.0     0.0
18      1.0      0.0      0.0      0.0     0.0     0.0     0.0
19      0.0      1.0      0.0      0.0     0.0     0.0     0.0

In [33]:
X_gk = pd.concat([x_normalized_gk, X_cat_encoded_gk], axis = 1)

X_gk.shape

print(x_normalized_gk.shape)
print(X_cat_encoded_gk.shape)

(1081, 53)
(1081, 7)

In [34]:
from sklearn.model_selection import train_test_split as tts

X_train_gk, X_test_gk, y_train_gk, y_test_gk=tts(X_gk, y_gk, test_size=.25)

In [35]:
X_train_gk

,Age,Growth,Value,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,DEF,PHY,GK,W/F_2 ★,W/F_3 ★,W/F_4 ★,W/F_5 ★,IR_2 ★,IR_3 ★,IR_4 ★
544,0.222222,0.500000,0.007554,0.321101,0.620690,0.24,0.119048,0.226415,0.024350,0.358382,...,0.377358,0.425926,0.413043,0.0,1.0,0.0,0.0,0.0,0.0,0.0
488,0.740741,0.000000,0.000504,0.376147,0.172414,0.32,0.214286,0.358491,0.170452,0.369942,...,0.396226,0.425926,0.326087,0.0,0.0,1.0,0.0,0.0,0.0,0.0
670,0.148148,0.416667,0.002878,0.229358,0.275862,0.08,0.119048,0.226415,0.121751,0.132948,...,0.264151,0.277778,0.326087,1.0,0.0,0.0,0.0,0.0,0.0,0.0
535,0.370370,0.166667,0.237410,0.412844,0.310345,0.36,0.166667,0.339623,0.219152,0.225434,...,0.509434,0.685185,0.804348,0.0,1.0,0.0,0.0,0.0,0.0,0.0
708,0.481481,0.000000,0.004676,0.513761,0.241379,0.36,0.309524,0.358491,0.365254,0.294798,...,0.584906,0.500000,0.413043,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,0.444444,0.041667,0.007914,0.513761,0.310345,0.32,0.190476,0.509434,0.267853,0.317919,...,0.566038,0.462963,0.478261,0.0,1.0,0.0,0.0,0.0,0.0,0.0
60,0.740741,0.000000,0.004317,0.513761,0.413793,0.40,0.214286,0.396226,0.267853,0.283237,...,0.415094,0.648148,0.543478,0.0,1.0,0.0,0.0,0.0,0.0,0.0
238,0.000000,0.416667,0.000432,0.266055,0.241379,0.12,0.214286,0.245283,0.097401,0.190751,...,0.150943,0.111111,0.086957,0.0,0.0,0.0,0.0,0.0,0.0,0.0
121,0.296296,0.166667,0.093525,0.513761,0.482759,0.44,0.285714,0.320755,0.219152,0.236994,...,0.433962,0.629630,0.673913,0.0,1.0,0.0,0.0,0.0,0.0,0.0
136,0.629630,0.000000,0.005036,0.339450,0.310345,0.32,0.142857,0.264151,0.170452,0.283237,...,0.396226,0.462963,0.456522,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
y_train_gk

5847    63
5250    60
7028    59
5779    81
7522    64
        ..
7805    66
584     70
2590    48
1246    75
1366    66
Name: OVA, Length: 810, dtype: int64

In [37]:
from sklearn.linear_model import LinearRegression as linreg

lm_gk = linreg()
lm_gk.fit(X_train_gk,y_train_gk)
y_pred_gk = lm_gk.predict(X_test_gk)

In [38]:
from sklearn.metrics import r2_score

predictions_gk = lm_gk.predict(X_train_gk)
r2_score(y_train_gk, predictions_gk)

0.9990592380872066

In [39]:
predictions_test_gk = lm_gk.predict(X_test_gk)
r2_score(y_test_gk, predictions_test_gk)

0.9990234082250947

In [40]:
display(y_test_gk[:5])
display(predictions_test_gk[:5])

10302    83
10399    59
6776     63
3857     80
403      72
Name: OVA, dtype: int64

array([83.05205137, 58.73707848, 62.91384166, 79.97473145, 72.1571879 ])